# Generated by Django 3.0.3 on 2020-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_timing_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_timing',
            name='timing',
            field=models.CharField(choices=[('1pm to 4pm', '1pm to 4pm'), ('4pm to 6pm', '4pm to 6pm'), ('10am to 1pm', '10am to 1pm')], max_length=200),
        ),
    ]
