# Generated by Django 3.0.3 on 2020-07-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='department',
            new_name='doctors',
        ),
    ]
