# Generated by Django 3.0.3 on 2020-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200724_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
